# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/arty-z7-i2s/PL/xdc/pinout_timing.xdc

# IP: C:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/arty-z7-i2s/PL/ip/i2s_rom/i2s_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2s_rom || ORIG_REF_NAME==i2s_rom} -quiet] -quiet

# IP: C:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/arty-z7-i2s/PL/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/i2s_rom.gen/sources_1/ip/i2s_rom/i2s_rom_ooc.xdc

# XDC: c:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/i2s_rom.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/i2s_rom.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/binup/HobbyProjects/ActiveProjects/Git_repos/microbuzz/projects/i2s_rom.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
